name: CI

on:
  push:
    branches:
      - main

jobs:
  lint-and-build:
    name: Lint and Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for outdated dependencies
        run: npm outdated || true

      - name: Run security audit
        run: npm audit || true

      - name: Run lint
        run: npm run lint

      - name: Type check
        run: npm run type-check || tsc --noEmit

      - name: Build project
        run: npm run build
        
      - name: Check bundle size
        run: npm run analyze || true